### ISSUE TITLE
Stupid error during npm install, in spite of the cancelling the installation

### ISSUE THREAD

**Issue by acarstoiu** [brandonocasey/npm-merge-driver-install#15]
I have disabled the installation of _npm-merge-driver_ by setting `NPM_MERGE_DRIVER_SKIP_INSTALL` to _true_ (shouldn't matter, according to the documentation). Still I get this:
```
>echo %NPM_MERGE_DRIVER_SKIP_INSTALL%
true

>npm i
...
3952 verbose stack Error: command failed
3952 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
3952 verbose stack     at ChildProcess.emit (node:events:390:28)
3952 verbose stack     at maybeClose (node:internal/child_process:1062:16)
3952 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3953 verbose pkgid npm-merge-driver-install@2.0.1
3954 verbose cwd XYZ
3955 verbose Windows_NT 10.0.19043
3956 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
3957 verbose node v17.0.1
3958 verbose npm  v8.1.0
3959 error code 1
3960 error path XYZ\node_modules\npm-merge-driver-install
3961 error command failed
3962 error command C:\Windows\system32\cmd.exe /d /s /c node src/install.js
3963 error XYZ\node_modules\npm-merge-driver-install\src\get-root.js:8
3963 error   const rootDir = gitRootResult.stdout.toString().trim();
3963 error                                        ^
3963 error
3963 error TypeError: Cannot read properties of null (reading 'toString')
3963 error     at getRoot (XYZ\node_modules\npm-merge-driver-install\src\get-root.js:8:40)
3963 error     at Object.<anonymous> (XYZ\node_modules\npm-merge-driver-install\src\install.js:7:41)
3963 error     at Module._compile (node:internal/modules/cjs/loader:1095:14)
3963 error     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
3963 error     at Module.load (node:internal/modules/cjs/loader:975:32)
3963 error     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
3963 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
3963 error     at node:internal/main/run_main_module:17:47
3963 error
3963 error Node.js v17.0.1
3964 verbose exit 1
```
First of all, it's a bug that it crashes, I suppose it happens so because I **don't** have _git_ installed. A second issue is that it seems to ignore the said environment variable.

**Comment by brandonocasey** [comment]
sorry about that, guess we need to make sure git is installed before trying to use it

**Comment by acarstoiu** [comment]
What about the ignored variable `NPM_MERGE_DRIVER_SKIP_INSTALL`?

**Comment by brandonocasey** [comment]
This should be fixed with `v2.0.2` I needed to null check the git get root result.
